from dataclasses import dataclass

from performance import Performance


@dataclass()
class PreResult:
    id: int = 0
    home_accurateCrosses: float = 0.0
    home_accurateFinalThirdPassesAgainst: float = 0.0
    home_accurateLongBalls: float = 0.0
    home_accurateOppositionHalfPasses: float = 0.0
    home_accurateOppositionHalfPassesAgainst: float = 0.0
    home_accurateOwnHalfPasses: float = 0.0
    home_accurateOwnHalfPassesAgainst: float = 0.0
    home_accuratePasses: float = 0.0
    home_accuratePassesAgainst: float = 0.0
    home_aerialDuelsWon: float = 0.0
    home_assists: float = 0.0
    home_averageBallPossession: float = 0.0
    home_avgRating: float = 0.0
    home_bigChances: float = 0.0
    home_bigChancesAgainst: float = 0.0
    home_bigChancesCreated: float = 0.0
    home_bigChancesCreatedAgainst: float = 0.0
    home_bigChancesMissed: float = 0.0
    home_bigChancesMissedAgainst: float = 0.0
    home_cleanSheets: float = 0.0
    home_clearances: float = 0.0
    home_clearancesAgainst: float = 0.0
    home_clearancesOffLine: float = 0.0
    home_corners: float = 0.0
    home_cornersAgainst: float = 0.0
    home_crossesSuccessfulAgainst: float = 0.0
    home_crossesTotalAgainst: float = 0.0
    home_dribbleAttempts: float = 0.0
    home_dribbleAttemptsTotalAgainst: float = 0.0
    home_dribbleAttemptsWonAgainst: float = 0.0
    home_duelsWon: float = 0.0
    home_errorsLeadingToGoal: float = 0.0
    home_errorsLeadingToGoalAgainst: float = 0.0
    home_errorsLeadingToShot: float = 0.0
    home_errorsLeadingToShotAgainst: float = 0.0
    home_fastBreakGoals: float = 0.0
    home_fastBreakShots: float = 0.0
    home_fastBreaks: float = 0.0
    home_fouls: float = 0.0
    home_freeKickGoals: float = 0.0
    home_freeKickShots: float = 0.0
    home_goalsConceded: float = 0.0
    home_goalsFromInsideTheBox: float = 0.0
    home_goalsFromOutsideTheBox: float = 0.0
    home_goalsScored: float = 0.0
    home_groundDuelsWon: float = 0.0
    home_headedGoals: float = 0.0
    home_hitWoodwork: float = 0.0
    home_hitWoodworkAgainst: float = 0.0
    home_interceptions: float = 0.0
    home_interceptionsAgainst: float = 0.0
    home_keyPassesAgainst: float = 0.0
    home_lastManTackles: float = 0.0
    home_leftFootGoals: float = 0.0
    home_longBallsSuccessfulAgainst: float = 0.0
    home_longBallsTotalAgainst: float = 0.0
    home_matches: float = 0.0
    home_offsides: float = 0.0
    home_offsidesAgainst: float = 0.0
    home_oppositionHalfPassesTotalAgainst: float = 0.0
    home_ownGoals: float = 0.0
    home_ownHalfPassesTotalAgainst: float = 0.0
    home_penaltiesCommited: float = 0.0
    home_penaltiesTaken: float = 0.0
    home_penaltyGoals: float = 0.0
    home_penaltyGoalsConceded: float = 0.0
    home_possessionLost: float = 0.0
    home_redCards: float = 0.0
    home_redCardsAgainst: float = 0.0
    home_rightFootGoals: float = 0.0
    home_saves: float = 0.0
    home_shots: float = 0.0
    home_shotsAgainst: float = 0.0
    home_shotsBlockedAgainst: float = 0.0
    home_shotsFromInsideTheBox: float = 0.0
    home_shotsFromInsideTheBoxAgainst: float = 0.0
    home_shotsFromOutsideTheBox: float = 0.0
    home_shotsFromOutsideTheBoxAgainst: float = 0.0
    home_shotsOffTarget: float = 0.0
    home_shotsOffTargetAgainst: float = 0.0
    home_shotsOnTarget: float = 0.0
    home_shotsOnTargetAgainst: float = 0.0
    home_successfulDribbles: float = 0.0
    home_tackles: float = 0.0
    home_tacklesAgainst: float = 0.0
    home_totalAerialDuels: float = 0.0
    home_totalCrosses: float = 0.0
    home_totalDuels: float = 0.0
    home_totalFinalThirdPassesAgainst: float = 0.0
    home_totalGroundDuels: float = 0.0
    home_totalLongBalls: float = 0.0
    home_totalOppositionHalfPasses: float = 0.0
    home_totalOwnHalfPasses: float = 0.0
    home_totalPasses: float = 0.0
    home_totalPassesAgainst: float = 0.0
    home_yellowCards: float = 0.0
    home_yellowCardsAgainst: float = 0.0
    home_yellowRedCards: float = 0.0
    away_accurateCrosses: float = 0.0
    away_accurateFinalThirdPassesAgainst: float = 0.0
    away_accurateLongBalls: float = 0.0
    away_accurateOppositionHalfPasses: float = 0.0
    away_accurateOppositionHalfPassesAgainst: float = 0.0
    away_accurateOwnHalfPasses: float = 0.0
    away_accurateOwnHalfPassesAgainst: float = 0.0
    away_accuratePasses: float = 0.0
    away_accuratePassesAgainst: float = 0.0
    away_aerialDuelsWon: float = 0.0
    away_assists: float = 0.0
    away_averageBallPossession: float = 0.0
    away_avgRating: float = 0.0
    away_bigChances: float = 0.0
    away_bigChancesAgainst: float = 0.0
    away_bigChancesCreated: float = 0.0
    away_bigChancesCreatedAgainst: float = 0.0
    away_bigChancesMissed: float = 0.0
    away_bigChancesMissedAgainst: float = 0.0
    away_cleanSheets: float = 0.0
    away_clearances: float = 0.0
    away_clearancesAgainst: float = 0.0
    away_clearancesOffLine: float = 0.0
    away_corners: float = 0.0
    away_cornersAgainst: float = 0.0
    away_crossesSuccessfulAgainst: float = 0.0
    away_crossesTotalAgainst: float = 0.0
    away_dribbleAttempts: float = 0.0
    away_dribbleAttemptsTotalAgainst: float = 0.0
    away_dribbleAttemptsWonAgainst: float = 0.0
    away_duelsWon: float = 0.0
    away_errorsLeadingToGoal: float = 0.0
    away_errorsLeadingToGoalAgainst: float = 0.0
    away_errorsLeadingToShot: float = 0.0
    away_errorsLeadingToShotAgainst: float = 0.0
    away_fastBreakGoals: float = 0.0
    away_fastBreakShots: float = 0.0
    away_fastBreaks: float = 0.0
    away_fouls: float = 0.0
    away_freeKickGoals: float = 0.0
    away_freeKickShots: float = 0.0
    away_goalsConceded: float = 0.0
    away_goalsFromInsideTheBox: float = 0.0
    away_goalsFromOutsideTheBox: float = 0.0
    away_goalsScored: float = 0.0
    away_groundDuelsWon: float = 0.0
    away_headedGoals: float = 0.0
    away_hitWoodwork: float = 0.0
    away_hitWoodworkAgainst: float = 0.0
    away_interceptions: float = 0.0
    away_interceptionsAgainst: float = 0.0
    away_keyPassesAgainst: float = 0.0
    away_lastManTackles: float = 0.0
    away_leftFootGoals: float = 0.0
    away_longBallsSuccessfulAgainst: float = 0.0
    away_longBallsTotalAgainst: float = 0.0
    away_matches: float = 0.0
    away_offsides: float = 0.0
    away_offsidesAgainst: float = 0.0
    away_oppositionHalfPassesTotalAgainst: float = 0.0
    away_ownGoals: float = 0.0
    away_ownHalfPassesTotalAgainst: float = 0.0
    away_penaltiesCommited: float = 0.0
    away_penaltiesTaken: float = 0.0
    away_penaltyGoals: float = 0.0
    away_penaltyGoalsConceded: float = 0.0
    away_possessionLost: float = 0.0
    away_redCards: float = 0.0
    away_redCardsAgainst: float = 0.0
    away_rightFootGoals: float = 0.0
    away_saves: float = 0.0
    away_shots: float = 0.0
    away_shotsAgainst: float = 0.0
    away_shotsBlockedAgainst: float = 0.0
    away_shotsFromInsideTheBox: float = 0.0
    away_shotsFromInsideTheBoxAgainst: float = 0.0
    away_shotsFromOutsideTheBox: float = 0.0
    away_shotsFromOutsideTheBoxAgainst: float = 0.0
    away_shotsOffTarget: float = 0.0
    away_shotsOffTargetAgainst: float = 0.0
    away_shotsOnTarget: float = 0.0
    away_shotsOnTargetAgainst: float = 0.0
    away_successfulDribbles: float = 0.0
    away_tackles: float = 0.0
    away_tacklesAgainst: float = 0.0
    away_totalAerialDuels: float = 0.0
    away_totalCrosses: float = 0.0
    away_totalDuels: float = 0.0
    away_totalFinalThirdPassesAgainst: float = 0.0
    away_totalGroundDuels: float = 0.0
    away_totalLongBalls: float = 0.0
    away_totalOppositionHalfPasses: float = 0.0
    away_totalOwnHalfPasses: float = 0.0
    away_totalPasses: float = 0.0
    away_totalPassesAgainst: float = 0.0
    away_yellowCards: float = 0.0
    away_yellowCardsAgainst: float = 0.0
    away_yellowRedCards: float = 0.0


    def __init__(self, id: int = 0, home_accurateCrosses=0.0,
    home_accurateFinalThirdPassesAgainst=0.0,
    home_accurateLongBalls=0.0,
    home_accurateOppositionHalfPasses=0.0,
    home_accurateOppositionHalfPassesAgainst=0.0,
    home_accurateOwnHalfPasses=0.0,
    home_accurateOwnHalfPassesAgainst=0.0,
    home_accuratePasses=0.0,
    home_accuratePassesAgainst=0.0,
    home_aerialDuelsWon=0.0,
    home_assists=0.0,
    home_averageBallPossession=0.0,
    home_avgRating=0.0,
    home_bigChances=0.0,
    home_bigChancesAgainst=0.0,
    home_bigChancesCreated=0.0,
    home_bigChancesCreatedAgainst=0.0,
    home_bigChancesMissed=0.0,
    home_bigChancesMissedAgainst=0.0,
    home_cleanSheets=0.0,
    home_clearances=0.0,
    home_clearancesAgainst=0.0,
    home_clearancesOffLine=0.0,
    home_corners=0.0,
    home_cornersAgainst=0.0,
    home_crossesSuccessfulAgainst=0.0,
    home_crossesTotalAgainst=0.0,
    home_dribbleAttempts=0.0,
    home_dribbleAttemptsTotalAgainst=0.0,
    home_dribbleAttemptsWonAgainst=0.0,
    home_duelsWon=0.0,
    home_errorsLeadingToGoal=0.0,
    home_errorsLeadingToGoalAgainst=0.0,
    home_errorsLeadingToShot=0.0,
    home_errorsLeadingToShotAgainst=0.0,
    home_fastBreakGoals=0.0,
    home_fastBreakShots=0.0,
    home_fastBreaks=0.0,
    home_fouls=0.0,
    home_freeKickGoals=0.0,
    home_freeKickShots=0.0,
    home_goalsConceded=0.0,
    home_goalsFromInsideTheBox=0.0,
    home_goalsFromOutsideTheBox=0.0,
    home_goalsScored=0.0,
    home_groundDuelsWon=0.0,
    home_headedGoals=0.0,
    home_hitWoodwork=0.0,
    home_hitWoodworkAgainst=0.0,
    home_interceptions=0.0,
    home_interceptionsAgainst=0.0,
    home_keyPassesAgainst=0.0,
    home_lastManTackles=0.0,
    home_leftFootGoals=0.0,
    home_longBallsSuccessfulAgainst=0.0,
    home_longBallsTotalAgainst=0.0,
    home_matches=0.0,
    home_offsides=0.0,
    home_offsidesAgainst=0.0,
    home_oppositionHalfPassesTotalAgainst=0.0,
    home_ownGoals=0.0,
    home_ownHalfPassesTotalAgainst=0.0,
    home_penaltiesCommited=0.0,
    home_penaltiesTaken=0.0,
    home_penaltyGoals=0.0,
    home_penaltyGoalsConceded=0.0,
    home_possessionLost=0.0,
    home_redCards=0.0,
    home_redCardsAgainst=0.0,
    home_rightFootGoals=0.0,
    home_saves=0.0,
    home_shots=0.0,
    home_shotsAgainst=0.0,
    home_shotsBlockedAgainst=0.0,
    home_shotsFromInsideTheBox=0.0,
    home_shotsFromInsideTheBoxAgainst=0.0,
    home_shotsFromOutsideTheBox=0.0,
    home_shotsFromOutsideTheBoxAgainst=0.0,
    home_shotsOffTarget=0.0,
    home_shotsOffTargetAgainst=0.0,
    home_shotsOnTarget=0.0,
    home_shotsOnTargetAgainst=0.0,
    home_successfulDribbles=0.0,
    home_tackles=0.0,
    home_tacklesAgainst=0.0,
    home_totalAerialDuels=0.0,
    home_totalCrosses=0.0,
    home_totalDuels=0.0,
    home_totalFinalThirdPassesAgainst=0.0,
    home_totalGroundDuels=0.0,
    home_totalLongBalls=0.0,
    home_totalOppositionHalfPasses=0.0,
    home_totalOwnHalfPasses=0.0,
    home_totalPasses=0.0,
    home_totalPassesAgainst=0.0,
    home_yellowCards=0.0,
    home_yellowCardsAgainst=0.0,
    home_yellowRedCards=0.0,
    away_accurateCrosses=0.0,
    away_accurateFinalThirdPassesAgainst=0.0,
    away_accurateLongBalls=0.0,
    away_accurateOppositionHalfPasses=0.0,
    away_accurateOppositionHalfPassesAgainst=0.0,
    away_accurateOwnHalfPasses=0.0,
    away_accurateOwnHalfPassesAgainst=0.0,
    away_accuratePasses=0.0,
    away_accuratePassesAgainst=0.0,
    away_aerialDuelsWon=0.0,
    away_assists=0.0,
    away_averageBallPossession=0.0,
    away_avgRating=0.0,
    away_bigChances=0.0,
    away_bigChancesAgainst=0.0,
    away_bigChancesCreated=0.0,
    away_bigChancesCreatedAgainst=0.0,
    away_bigChancesMissed=0.0,
    away_bigChancesMissedAgainst=0.0,
    away_cleanSheets=0.0,
    away_clearances=0.0,
    away_clearancesAgainst=0.0,
    away_clearancesOffLine=0.0,
    away_corners=0.0,
    away_cornersAgainst=0.0,
    away_crossesSuccessfulAgainst=0.0,
    away_crossesTotalAgainst=0.0,
    away_dribbleAttempts=0.0,
    away_dribbleAttemptsTotalAgainst=0.0,
    away_dribbleAttemptsWonAgainst=0.0,
    away_duelsWon=0.0,
    away_errorsLeadingToGoal=0.0,
    away_errorsLeadingToGoalAgainst=0.0,
    away_errorsLeadingToShot=0.0,
    away_errorsLeadingToShotAgainst=0.0,
    away_fastBreakGoals=0.0,
    away_fastBreakShots=0.0,
    away_fastBreaks=0.0,
    away_fouls=0.0,
    away_freeKickGoals=0.0,
    away_freeKickShots=0.0,
    away_goalsConceded=0.0,
    away_goalsFromInsideTheBox=0.0,
    away_goalsFromOutsideTheBox=0.0,
    away_goalsScored=0.0,
    away_groundDuelsWon=0.0,
    away_headedGoals=0.0,
    away_hitWoodwork=0.0,
    away_hitWoodworkAgainst=0.0,
    away_interceptions=0.0,
    away_interceptionsAgainst=0.0,
    away_keyPassesAgainst=0.0,
    away_lastManTackles=0.0,
    away_leftFootGoals=0.0,
    away_longBallsSuccessfulAgainst=0.0,
    away_longBallsTotalAgainst=0.0,
    away_matches=0.0,
    away_offsides=0.0,
    away_offsidesAgainst=0.0,
    away_oppositionHalfPassesTotalAgainst=0.0,
    away_ownGoals=0.0,
    away_ownHalfPassesTotalAgainst=0.0,
    away_penaltiesCommited=0.0,
    away_penaltiesTaken=0.0,
    away_penaltyGoals=0.0,
    away_penaltyGoalsConceded=0.0,
    away_possessionLost=0.0,
    away_redCards=0.0,
    away_redCardsAgainst=0.0,
    away_rightFootGoals=0.0,
    away_saves=0.0,
    away_shots=0.0,
    away_shotsAgainst=0.0,
    away_shotsBlockedAgainst=0.0,
    away_shotsFromInsideTheBox=0.0,
    away_shotsFromInsideTheBoxAgainst=0.0,
    away_shotsFromOutsideTheBox=0.0,
    away_shotsFromOutsideTheBoxAgainst=0.0,
    away_shotsOffTarget=0.0,
    away_shotsOffTargetAgainst=0.0,
    away_shotsOnTarget=0.0,
    away_shotsOnTargetAgainst=0.0,
    away_successfulDribbles=0.0,
    away_tackles=0.0,
    away_tacklesAgainst=0.0,
    away_totalAerialDuels=0.0,
    away_totalCrosses=0.0,
    away_totalDuels=0.0,
    away_totalFinalThirdPassesAgainst=0.0,
    away_totalGroundDuels=0.0,
    away_totalLongBalls=0.0,
    away_totalOppositionHalfPasses=0.0,
    away_totalOwnHalfPasses=0.0,
    away_totalPasses=0.0,
    away_totalPassesAgainst=0.0,
    away_yellowCards=0.0,
    away_yellowCardsAgainst=0.0,
    away_yellowRedCards=0.0, home: Performance = None, away: Performance = None):
        self.id = id
        if home is not None:
            self.home_accurateCrosses = home.accurateCrosses
            self.home_accurateFinalThirdPassesAgainst = home.accurateFinalThirdPassesAgainst
            self.home_accurateLongBalls = home.accurateLongBalls
            self.home_accurateOppositionHalfPasses = home.accurateOppositionHalfPasses
            self.home_accurateOppositionHalfPassesAgainst = home.accurateOppositionHalfPassesAgainst
            self.home_accurateOwnHalfPasses = home.accurateOwnHalfPasses
            self.home_accurateOwnHalfPassesAgainst = home.accurateOwnHalfPassesAgainst
            self.home_accuratePasses = home.accuratePasses
            self.home_accuratePassesAgainst = home.accuratePassesAgainst
            self.home_aerialDuelsWon = home.aerialDuelsWon
            self.home_assists = home.assists
            self.home_averageBallPossession = home.averageBallPossession
            self.home_avgRating = home.avgRating
            self.home_bigChances = home.bigChances
            self.home_bigChancesAgainst = home.bigChancesAgainst
            self.home_bigChancesCreated = home.bigChancesCreated
            self.home_bigChancesCreatedAgainst = home.bigChancesCreatedAgainst
            self.home_bigChancesMissed = home.bigChancesMissed
            self.home_bigChancesMissedAgainst = home.bigChancesMissedAgainst
            self.home_cleanSheets = home.cleanSheets
            self.home_clearances = home.clearances
            self.home_clearancesAgainst = home.clearancesAgainst
            self.home_clearancesOffLine = home.clearancesOffLine
            self.home_corners = home.corners
            self.home_cornersAgainst = home.cornersAgainst
            self.home_crossesSuccessfulAgainst = home.crossesSuccessfulAgainst
            self.home_crossesTotalAgainst = home.crossesTotalAgainst
            self.home_dribbleAttempts = home.dribbleAttempts
            self.home_dribbleAttemptsTotalAgainst = home.dribbleAttemptsTotalAgainst
            self.home_dribbleAttemptsWonAgainst = home.dribbleAttemptsWonAgainst
            self.home_duelsWon = home.duelsWon
            self.home_errorsLeadingToGoal = home.errorsLeadingToGoal
            self.home_errorsLeadingToGoalAgainst = home.errorsLeadingToGoalAgainst
            self.home_errorsLeadingToShot = home.errorsLeadingToShot
            self.home_errorsLeadingToShotAgainst = home.errorsLeadingToShotAgainst
            self.home_fastBreakGoals = home.fastBreakGoals
            self.home_fastBreakShots = home.fastBreakShots
            self.home_fastBreaks = home.fastBreaks
            self.home_fouls = home.fouls
            self.home_freeKickGoals = home.freeKickGoals
            self.home_freeKickShots = home.freeKickShots
            self.home_goalsConceded = home.goalsConceded
            self.home_goalsFromInsideTheBox = home.goalsFromInsideTheBox
            self.home_goalsFromOutsideTheBox = home.goalsFromOutsideTheBox
            self.home_goalsScored = home.goalsScored
            self.home_groundDuelsWon = home.groundDuelsWon
            self.home_headedGoals = home.headedGoals
            self.home_hitWoodwork = home.hitWoodwork
            self.home_hitWoodworkAgainst = home.hitWoodworkAgainst
            self.home_interceptions = home.interceptions
            self.home_interceptionsAgainst = home.interceptionsAgainst
            self.home_keyPassesAgainst = home.keyPassesAgainst
            self.home_lastManTackles = home.lastManTackles
            self.home_leftFootGoals = home.leftFootGoals
            self.home_longBallsSuccessfulAgainst = home.longBallsSuccessfulAgainst
            self.home_longBallsTotalAgainst = home.longBallsTotalAgainst
            self.home_matches = home.matches
            self.home_offsides = home.offsides
            self.home_offsidesAgainst = home.offsidesAgainst
            self.home_oppositionHalfPassesTotalAgainst = home.oppositionHalfPassesTotalAgainst
            self.home_ownGoals = home.ownGoals
            self.home_ownHalfPassesTotalAgainst = home.ownHalfPassesTotalAgainst
            self.home_penaltiesCommited = home.penaltiesCommited
            self.home_penaltiesTaken = home.penaltiesTaken
            self.home_penaltyGoals = home.penaltyGoals
            self.home_penaltyGoalsConceded = home.penaltyGoalsConceded
            self.home_possessionLost = home.possessionLost
            self.home_redCards = home.redCards
            self.home_redCardsAgainst = home.redCardsAgainst
            self.home_rightFootGoals = home.rightFootGoals
            self.home_saves = home.saves
            self.home_shots = home.shots
            self.home_shotsAgainst = home.shotsAgainst
            self.home_shotsBlockedAgainst = home.shotsBlockedAgainst
            self.home_shotsFromInsideTheBox = home.shotsFromInsideTheBox
            self.home_shotsFromInsideTheBoxAgainst = home.shotsFromInsideTheBoxAgainst
            self.home_shotsFromOutsideTheBox = home.shotsFromOutsideTheBox
            self.home_shotsFromOutsideTheBoxAgainst = home.shotsFromOutsideTheBoxAgainst
            self.home_shotsOffTarget = home.shotsOffTarget
            self.home_shotsOffTargetAgainst = home.shotsOffTargetAgainst
            self.home_shotsOnTarget = home.shotsOnTarget
            self.home_shotsOnTargetAgainst = home.shotsOnTargetAgainst
            self.home_successfulDribbles = home.successfulDribbles
            self.home_tackles = home.tackles
            self.home_tacklesAgainst = home.tacklesAgainst
            self.home_totalAerialDuels = home.totalAerialDuels
            self.home_totalCrosses = home.totalCrosses
            self.home_totalDuels = home.totalDuels
            self.home_totalFinalThirdPassesAgainst = home.totalFinalThirdPassesAgainst
            self.home_totalGroundDuels = home.totalGroundDuels
            self.home_totalLongBalls = home.totalLongBalls
            self.home_totalOppositionHalfPasses = home.totalOppositionHalfPasses
            self.home_totalOwnHalfPasses = home.totalOwnHalfPasses
            self.home_totalPasses = home.totalPasses
            self.home_totalPassesAgainst = home.totalPassesAgainst
            self.home_yellowCards = home.yellowCards
            self.home_yellowCardsAgainst = home.yellowCardsAgainst
            self.home_yellowRedCards = home.yellowRedCards
        if away is not None:
            self.away_accurateCrosses = away.accurateCrosses
            self.away_accurateFinalThirdPassesAgainst = away.accurateFinalThirdPassesAgainst
            self.away_accurateLongBalls = away.accurateLongBalls
            self.away_accurateOppositionHalfPasses = away.accurateOppositionHalfPasses
            self.away_accurateOppositionHalfPassesAgainst = away.accurateOppositionHalfPassesAgainst
            self.away_accurateOwnHalfPasses = away.accurateOwnHalfPasses
            self.away_accurateOwnHalfPassesAgainst = away.accurateOwnHalfPassesAgainst
            self.away_accuratePasses = away.accuratePasses
            self.away_accuratePassesAgainst = away.accuratePassesAgainst
            self.away_aerialDuelsWon = away.aerialDuelsWon
            self.away_assists = away.assists
            self.away_averageBallPossession = away.averageBallPossession
            self.away_avgRating = away.avgRating
            self.away_bigChances = away.bigChances
            self.away_bigChancesAgainst = away.bigChancesAgainst
            self.away_bigChancesCreated = away.bigChancesCreated
            self.away_bigChancesCreatedAgainst = away.bigChancesCreatedAgainst
            self.away_bigChancesMissed = away.bigChancesMissed
            self.away_bigChancesMissedAgainst = away.bigChancesMissedAgainst
            self.away_cleanSheets = away.cleanSheets
            self.away_clearances = away.clearances
            self.away_clearancesAgainst = away.clearancesAgainst
            self.away_clearancesOffLine = away.clearancesOffLine
            self.away_corners = away.corners
            self.away_cornersAgainst = away.cornersAgainst
            self.away_crossesSuccessfulAgainst = away.crossesSuccessfulAgainst
            self.away_crossesTotalAgainst = away.crossesTotalAgainst
            self.away_dribbleAttempts = away.dribbleAttempts
            self.away_dribbleAttemptsTotalAgainst = away.dribbleAttemptsTotalAgainst
            self.away_dribbleAttemptsWonAgainst = away.dribbleAttemptsWonAgainst
            self.away_duelsWon = away.duelsWon
            self.away_errorsLeadingToGoal = away.errorsLeadingToGoal
            self.away_errorsLeadingToGoalAgainst = away.errorsLeadingToGoalAgainst
            self.away_errorsLeadingToShot = away.errorsLeadingToShot
            self.away_errorsLeadingToShotAgainst = away.errorsLeadingToShotAgainst
            self.away_fastBreakGoals = away.fastBreakGoals
            self.away_fastBreakShots = away.fastBreakShots
            self.away_fastBreaks = away.fastBreaks
            self.away_fouls = away.fouls
            self.away_freeKickGoals = away.freeKickGoals
            self.away_freeKickShots = away.freeKickShots
            self.away_goalsConceded = away.goalsConceded
            self.away_goalsFromInsideTheBox = away.goalsFromInsideTheBox
            self.away_goalsFromOutsideTheBox = away.goalsFromOutsideTheBox
            self.away_goalsScored = away.goalsScored
            self.away_groundDuelsWon = away.groundDuelsWon
            self.away_headedGoals = away.headedGoals
            self.away_hitWoodwork = away.hitWoodwork
            self.away_hitWoodworkAgainst = away.hitWoodworkAgainst
            self.away_interceptions = away.interceptions
            self.away_interceptionsAgainst = away.interceptionsAgainst
            self.away_keyPassesAgainst = away.keyPassesAgainst
            self.away_lastManTackles = away.lastManTackles
            self.away_leftFootGoals = away.leftFootGoals
            self.away_longBallsSuccessfulAgainst = away.longBallsSuccessfulAgainst
            self.away_longBallsTotalAgainst = away.longBallsTotalAgainst
            self.away_matches = away.matches
            self.away_offsides = away.offsides
            self.away_offsidesAgainst = away.offsidesAgainst
            self.away_oppositionHalfPassesTotalAgainst = away.oppositionHalfPassesTotalAgainst
            self.away_ownGoals = away.ownGoals
            self.away_ownHalfPassesTotalAgainst = away.ownHalfPassesTotalAgainst
            self.away_penaltiesCommited = away.penaltiesCommited
            self.away_penaltiesTaken = away.penaltiesTaken
            self.away_penaltyGoals = away.penaltyGoals
            self.away_penaltyGoalsConceded = away.penaltyGoalsConceded
            self.away_possessionLost = away.possessionLost
            self.away_redCards = away.redCards
            self.away_redCardsAgainst = away.redCardsAgainst
            self.away_rightFootGoals = away.rightFootGoals
            self.away_saves = away.saves
            self.away_shots = away.shots
            self.away_shotsAgainst = away.shotsAgainst
            self.away_shotsBlockedAgainst = away.shotsBlockedAgainst
            self.away_shotsFromInsideTheBox = away.shotsFromInsideTheBox
            self.away_shotsFromInsideTheBoxAgainst = away.shotsFromInsideTheBoxAgainst
            self.away_shotsFromOutsideTheBox = away.shotsFromOutsideTheBox
            self.away_shotsFromOutsideTheBoxAgainst = away.shotsFromOutsideTheBoxAgainst
            self.away_shotsOffTarget = away.shotsOffTarget
            self.away_shotsOffTargetAgainst = away.shotsOffTargetAgainst
            self.away_shotsOnTarget = away.shotsOnTarget
            self.away_shotsOnTargetAgainst = away.shotsOnTargetAgainst
            self.away_successfulDribbles = away.successfulDribbles
            self.away_tackles = away.tackles
            self.away_tacklesAgainst = away.tacklesAgainst
            self.away_totalAerialDuels = away.totalAerialDuels
            self.away_totalCrosses = away.totalCrosses
            self.away_totalDuels = away.totalDuels
            self.away_totalFinalThirdPassesAgainst = away.totalFinalThirdPassesAgainst
            self.away_totalGroundDuels = away.totalGroundDuels
            self.away_totalLongBalls = away.totalLongBalls
            self.away_totalOppositionHalfPasses = away.totalOppositionHalfPasses
            self.away_totalOwnHalfPasses = away.totalOwnHalfPasses
            self.away_totalPasses = away.totalPasses
            self.away_totalPassesAgainst = away.totalPassesAgainst
            self.away_yellowCards = away.yellowCards
            self.away_yellowCardsAgainst = away.yellowCardsAgainst
            self.away_yellowRedCards = away.yellowRedCards
        if home is None and away is None:
            self.home_accurateCrosses = home_accurateCrosses
            self.home_accurateFinalThirdPassesAgainst = home_accurateFinalThirdPassesAgainst
            self.home_accurateLongBalls = home_accurateLongBalls
            self.home_accurateOppositionHalfPasses = home_accurateOppositionHalfPasses
            self.home_accurateOppositionHalfPassesAgainst = home_accurateOppositionHalfPassesAgainst
            self.home_accurateOwnHalfPasses = home_accurateOwnHalfPasses
            self.home_accurateOwnHalfPassesAgainst = home_accurateOwnHalfPassesAgainst
            self.home_accuratePasses = home_accuratePasses
            self.home_accuratePassesAgainst = home_accuratePassesAgainst
            self.home_aerialDuelsWon = home_aerialDuelsWon
            self.home_assists = home_assists
            self.home_averageBallPossession = home_averageBallPossession
            self.home_avgRating = home_avgRating
            self.home_bigChances = home_bigChances
            self.home_bigChancesAgainst = home_bigChancesAgainst
            self.home_bigChancesCreated = home_bigChancesCreated
            self.home_bigChancesCreatedAgainst = home_bigChancesCreatedAgainst
            self.home_bigChancesMissed = home_bigChancesMissed
            self.home_bigChancesMissedAgainst = home_bigChancesMissedAgainst
            self.home_cleanSheets = home_cleanSheets
            self.home_clearances = home_clearances
            self.home_clearancesAgainst = home_clearancesAgainst
            self.home_clearancesOffLine = home_clearancesOffLine
            self.home_corners = home_corners
            self.home_cornersAgainst = home_cornersAgainst
            self.home_crossesSuccessfulAgainst = home_crossesSuccessfulAgainst
            self.home_crossesTotalAgainst = home_crossesTotalAgainst
            self.home_dribbleAttempts = home_dribbleAttempts
            self.home_dribbleAttemptsTotalAgainst = home_dribbleAttemptsTotalAgainst
            self.home_dribbleAttemptsWonAgainst = home_dribbleAttemptsWonAgainst
            self.home_duelsWon = home_duelsWon
            self.home_errorsLeadingToGoal = home_errorsLeadingToGoal
            self.home_errorsLeadingToGoalAgainst = home_errorsLeadingToGoalAgainst
            self.home_errorsLeadingToShot = home_errorsLeadingToShot
            self.home_errorsLeadingToShotAgainst = home_errorsLeadingToShotAgainst
            self.home_fastBreakGoals = home_fastBreakGoals
            self.home_fastBreakShots = home_fastBreakShots
            self.home_fastBreaks = home_fastBreaks
            self.home_fouls = home_fouls
            self.home_freeKickGoals = home_freeKickGoals
            self.home_freeKickShots = home_freeKickShots
            self.home_goalsConceded = home_goalsConceded
            self.home_goalsFromInsideTheBox = home_goalsFromInsideTheBox
            self.home_goalsFromOutsideTheBox = home_goalsFromOutsideTheBox
            self.home_goalsScored = home_goalsScored
            self.home_groundDuelsWon = home_groundDuelsWon
            self.home_headedGoals = home_headedGoals
            self.home_hitWoodwork = home_hitWoodwork
            self.home_hitWoodworkAgainst = home_hitWoodworkAgainst
            self.home_interceptions = home_interceptions
            self.home_interceptionsAgainst = home_interceptionsAgainst
            self.home_keyPassesAgainst = home_keyPassesAgainst
            self.home_lastManTackles = home_lastManTackles
            self.home_leftFootGoals = home_leftFootGoals
            self.home_longBallsSuccessfulAgainst = home_longBallsSuccessfulAgainst
            self.home_longBallsTotalAgainst = home_longBallsTotalAgainst
            self.home_matches = home_matches
            self.home_offsides = home_offsides
            self.home_offsidesAgainst = home_offsidesAgainst
            self.home_oppositionHalfPassesTotalAgainst = home_oppositionHalfPassesTotalAgainst
            self.home_ownGoals = home_ownGoals
            self.home_ownHalfPassesTotalAgainst = home_ownHalfPassesTotalAgainst
            self.home_penaltiesCommited = home_penaltiesCommited
            self.home_penaltiesTaken = home_penaltiesTaken
            self.home_penaltyGoals = home_penaltyGoals
            self.home_penaltyGoalsConceded = home_penaltyGoalsConceded
            self.home_possessionLost = home_possessionLost
            self.home_redCards = home_redCards
            self.home_redCardsAgainst = home_redCardsAgainst
            self.home_rightFootGoals = home_rightFootGoals
            self.home_saves = home_saves
            self.home_shots = home_shots
            self.home_shotsAgainst = home_shotsAgainst
            self.home_shotsBlockedAgainst = home_shotsBlockedAgainst
            self.home_shotsFromInsideTheBox = home_shotsFromInsideTheBox
            self.home_shotsFromInsideTheBoxAgainst = home_shotsFromInsideTheBoxAgainst
            self.home_shotsFromOutsideTheBox = home_shotsFromOutsideTheBox
            self.home_shotsFromOutsideTheBoxAgainst = home_shotsFromOutsideTheBoxAgainst
            self.home_shotsOffTarget = home_shotsOffTarget
            self.home_shotsOffTargetAgainst = home_shotsOffTargetAgainst
            self.home_shotsOnTarget = home_shotsOnTarget
            self.home_shotsOnTargetAgainst = home_shotsOnTargetAgainst
            self.home_successfulDribbles = home_successfulDribbles
            self.home_tackles = home_tackles
            self.home_tacklesAgainst = home_tacklesAgainst
            self.home_totalAerialDuels = home_totalAerialDuels
            self.home_totalCrosses = home_totalCrosses
            self.home_totalDuels = home_totalDuels
            self.home_totalFinalThirdPassesAgainst = home_totalFinalThirdPassesAgainst
            self.home_totalGroundDuels = home_totalGroundDuels
            self.home_totalLongBalls = home_totalLongBalls
            self.home_totalOppositionHalfPasses = home_totalOppositionHalfPasses
            self.home_totalOwnHalfPasses = home_totalOwnHalfPasses
            self.home_totalPasses = home_totalPasses
            self.home_totalPassesAgainst = home_totalPassesAgainst
            self.home_yellowCards = home_yellowCards
            self.home_yellowCardsAgainst = home_yellowCardsAgainst
            self.home_yellowRedCards = home_yellowRedCards
            self.away_accurateCrosses = away_accurateCrosses
            self.away_accurateFinalThirdPassesAgainst = away_accurateFinalThirdPassesAgainst
            self.away_accurateLongBalls = away_accurateLongBalls
            self.away_accurateOppositionHalfPasses = away_accurateOppositionHalfPasses
            self.away_accurateOppositionHalfPassesAgainst = away_accurateOppositionHalfPassesAgainst
            self.away_accurateOwnHalfPasses = away_accurateOwnHalfPasses
            self.away_accurateOwnHalfPassesAgainst = away_accurateOwnHalfPassesAgainst
            self.away_accuratePasses = away_accuratePasses
            self.away_accuratePassesAgainst = away_accuratePassesAgainst
            self.away_aerialDuelsWon = away_aerialDuelsWon
            self.away_assists = away_assists
            self.away_averageBallPossession = away_averageBallPossession
            self.away_avgRating = away_avgRating
            self.away_bigChances = away_bigChances
            self.away_bigChancesAgainst = away_bigChancesAgainst
            self.away_bigChancesCreated = away_bigChancesCreated
            self.away_bigChancesCreatedAgainst = away_bigChancesCreatedAgainst
            self.away_bigChancesMissed = away_bigChancesMissed
            self.away_bigChancesMissedAgainst = away_bigChancesMissedAgainst
            self.away_cleanSheets = away_cleanSheets
            self.away_clearances = away_clearances
            self.away_clearancesAgainst = away_clearancesAgainst
            self.away_clearancesOffLine = away_clearancesOffLine
            self.away_corners = away_corners
            self.away_cornersAgainst = away_cornersAgainst
            self.away_crossesSuccessfulAgainst = away_crossesSuccessfulAgainst
            self.away_crossesTotalAgainst = away_crossesTotalAgainst
            self.away_dribbleAttempts = away_dribbleAttempts
            self.away_dribbleAttemptsTotalAgainst = away_dribbleAttemptsTotalAgainst
            self.away_dribbleAttemptsWonAgainst = away_dribbleAttemptsWonAgainst
            self.away_duelsWon = away_duelsWon
            self.away_errorsLeadingToGoal = away_errorsLeadingToGoal
            self.away_errorsLeadingToGoalAgainst = away_errorsLeadingToGoalAgainst
            self.away_errorsLeadingToShot = away_errorsLeadingToShot
            self.away_errorsLeadingToShotAgainst = away_errorsLeadingToShotAgainst
            self.away_fastBreakGoals = away_fastBreakGoals
            self.away_fastBreakShots = away_fastBreakShots
            self.away_fastBreaks = away_fastBreaks
            self.away_fouls = away_fouls
            self.away_freeKickGoals = away_freeKickGoals
            self.away_freeKickShots = away_freeKickShots
            self.away_goalsConceded = away_goalsConceded
            self.away_goalsFromInsideTheBox = away_goalsFromInsideTheBox
            self.away_goalsFromOutsideTheBox = away_goalsFromOutsideTheBox
            self.away_goalsScored = away_goalsScored
            self.away_groundDuelsWon = away_groundDuelsWon
            self.away_headedGoals = away_headedGoals
            self.away_hitWoodwork = away_hitWoodwork
            self.away_hitWoodworkAgainst = away_hitWoodworkAgainst
            self.away_interceptions = away_interceptions
            self.away_interceptionsAgainst = away_interceptionsAgainst
            self.away_keyPassesAgainst = away_keyPassesAgainst
            self.away_lastManTackles = away_lastManTackles
            self.away_leftFootGoals = away_leftFootGoals
            self.away_longBallsSuccessfulAgainst = away_longBallsSuccessfulAgainst
            self.away_longBallsTotalAgainst = away_longBallsTotalAgainst
            self.away_matches = away_matches
            self.away_offsides = away_offsides
            self.away_offsidesAgainst = away_offsidesAgainst
            self.away_oppositionHalfPassesTotalAgainst = away_oppositionHalfPassesTotalAgainst
            self.away_ownGoals = away_ownGoals
            self.away_ownHalfPassesTotalAgainst = away_ownHalfPassesTotalAgainst
            self.away_penaltiesCommited = away_penaltiesCommited
            self.away_penaltiesTaken = away_penaltiesTaken
            self.away_penaltyGoals = away_penaltyGoals
            self.away_penaltyGoalsConceded = away_penaltyGoalsConceded
            self.away_possessionLost = away_possessionLost
            self.away_redCards = away_redCards
            self.away_redCardsAgainst = away_redCardsAgainst
            self.away_rightFootGoals = away_rightFootGoals
            self.away_saves = away_saves
            self.away_shots = away_shots
            self.away_shotsAgainst = away_shotsAgainst
            self.away_shotsBlockedAgainst = away_shotsBlockedAgainst
            self.away_shotsFromInsideTheBox = away_shotsFromInsideTheBox
            self.away_shotsFromInsideTheBoxAgainst = away_shotsFromInsideTheBoxAgainst
            self.away_shotsFromOutsideTheBox = away_shotsFromOutsideTheBox
            self.away_shotsFromOutsideTheBoxAgainst = away_shotsFromOutsideTheBoxAgainst
            self.away_shotsOffTarget = away_shotsOffTarget
            self.away_shotsOffTargetAgainst = away_shotsOffTargetAgainst
            self.away_shotsOnTarget = away_shotsOnTarget
            self.away_shotsOnTargetAgainst = away_shotsOnTargetAgainst
            self.away_successfulDribbles = away_successfulDribbles
            self.away_tackles = away_tackles
            self.away_tacklesAgainst = away_tacklesAgainst
            self.away_totalAerialDuels = away_totalAerialDuels
            self.away_totalCrosses = away_totalCrosses
            self.away_totalDuels = away_totalDuels
            self.away_totalFinalThirdPassesAgainst = away_totalFinalThirdPassesAgainst
            self.away_totalGroundDuels = away_totalGroundDuels
            self.away_totalLongBalls = away_totalLongBalls
            self.away_totalOppositionHalfPasses = away_totalOppositionHalfPasses
            self.away_totalOwnHalfPasses = away_totalOwnHalfPasses
            self.away_totalPasses = away_totalPasses
            self.away_totalPassesAgainst = away_totalPassesAgainst
            self.away_yellowCards = away_yellowCards
            self.away_yellowCardsAgainst = away_yellowCardsAgainst
            self.away_yellowRedCards = away_yellowRedCards

    def __eq__(self, other):
        if type(other) is dict:
            return self.id == other['id']
        else:
            return self.id == other.id

    def __hash__(self):
        return hash(self.id)
